### ISSUE TITLE
Outgoing connections dropping on beta3

### ISSUE THREAD

**Issue by geomad** [paradigmxyz/reth#7302]
### Describe the bug

I run reth including the following arguments:  `--max-outbound-peers 25 --max-inbound-peers 15`
While reth was working as expected up to beta2 , after upgrading to beta3 the outgoing connections dropped to `1` , which I suspect its just my trusted node.

![image](https://github.com/paradigmxyz/reth/assets/7707517/8e9a8204-cebd-43ef-9d83-cb2116320701)

### Steps to reproduce

run reth with `--max-outbound-peers 25 --max-inbound-peers 15`

### Platform(s)

Linux (x86)

### What version/commit are you on?

reth Version: 0.2.0-beta.3
Commit SHA: 273f3c734

### What database version are you on?

2

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by mattsse** [comment]
this is most likely fixed by

https://github.com/paradigmxyz/reth/pull/7219

**Comment by geomad** [comment]
I upgraded to latest master, and its looking good so far. I will reopen if there are any issues thanks!

**Comment by mattsse** [comment]
thanks, I have a hunch that there's still something odd, so please lmk if you notice anything

**Comment by geomad** [comment]
@mattsse It looks like that after running fine for a few hours the issue is back!
![Screenshot_20240323_221632_Brave](https://github.com/paradigmxyz/reth/assets/7707517/b920bed9-a394-490d-b56d-250d83bc6a78)
Right now I'm on Commit SHA: 88186a257

**Comment by geomad** [comment]
@mattsse I've been running 61801b98b for 24 hours now and going great so far! I will keep monitoring another day and will close afterwards, thanks!
